min_fit_clients: 1
min_evaluate_clients: 1
min_available_clients: 1
num_rounds: 5
fraction_fit: 1.0
fraction_evaluate: 1.0
server_eval: false
val_batch_size: 128
server_param_init: true
stop_by_accuracy: false
accuracy_level: 0.8
collect_metrics_interval: 60
