defaults:
  - base_main
  - net: default
  - dataset: default
  - fl_server: default
  - fl_client: default
  - _self_

exp_name: "my_experiment"
log_dir: "static/logs/${exp_name}-${now:%m-%d_%H-%M-%S}"

hydra:
  run:
    dir: ${log_dir}
  job:
    name: ${exp_name}